import Head from "next/head";
import PostsListContainer from "../containers/PostsListContainer";
import withAuth from "../shared-components/withAuth";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostsListContainer />
    </>
  );
};

export default withAuth(Home);
