import Head from "next/head";
import { PostsQuery, usePostsQuery } from "../generated/graphql";
import graphqlRequestClient from "../lib/clients/graphqlRequestClient";

export default function Home() {
  const { data } = usePostsQuery<PostsQuery, Error>(graphqlRequestClient, {});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && data.posts.map((item) => <div key={item.id}>{item.title}</div>)}
    </>
  );
}
